Update integration test to only run on PR from dev to master

diff --git a/.github/workflows/integration_tests.yaml b/.github/workflows/integration_tests.yaml
--- a/.github/workflows/integration_tests.yaml
+++ b/.github/workflows/integration_tests.yaml
@@ -18,6 +18,11 @@ jobs:
       SUPABASE_DB_PORT: ${{ secrets.STAGING_DB_PORT }}
 
     steps:
+      - name: Check branch
+        if: github.base_ref == 'master' && github.head_ref != 'dev'
+        run: |
+          echo "ERROR: Integration tests can only be run on pull requests from dev to master."
+          exit 1
       - name: Checkout Repo Content
         uses: actions/checkout@v3
       - name: Setup Python
